server:
    port: 8061
spring:
    application:
        name: xxl_job_test


xxl:
    job:
        admin:
            addresses: http://localhost:8060/xxl-job-admin
        accessToken: 123456
        executor:
            appname: xxl-job-test
            ip: 192.168.0.103
            address: ""
            port: -1
            logpath: /log
            logretentiondays: "30"