server:
    port: 9999

spring:
  servlet:
      #控制文件上传的大小
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB

minio:
    endpoint: http://192.168.86.128:9000
    access-key: admin
    secret-key: 123456789
    bucket: test