server:
  port: 9994

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:9994/**"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
      routes:
        - id: system_route_1
          uri: http://localhost:9991
          predicates:
            - Path=/error/**
        - id: system_route_2
          uri: http://localhost:9991
          predicates:
            - Path=/dept/**
          filters:
            - name: CircuitBreaker
              args:
                name: cirA
                fallbackUri: forward:/error/info
                statusCodes:
                  - 500
                  - 404
                  - "NOT_FOUND"
        - id: role_route
          uri: lb://system
          predicates:
            - Path=/role/**
#        - id: system_route_3
#          uri: http://localhost:9991
#          predicates:
#            - Header=token,123456
#            - Path=/users/**
#        - id: home_route
#          uri: lb://home
#          predicates:
#            - Path=/tool/**
#        - id: weight_route_1
#          uri: http://localhost:9992
#          predicates:
#            - Weight=group1,2
#        - id: weight_route_2
#          uri: http://localhost:9993
#          predicates:
#            - Weight=group1,8
    #配置服务注册与发现
    consul:
      host: localhost
      port: 8500
      discovery:
        #配置服务名称
        service-name: ${spring.application.name}
        #配置服务实例id
        instance-id: ${spring.application.name}-${server.port}
        #是否注册服务
        register: true
        #使用ip地址注册
        prefer-ip-address: true
        #本服务ip
        ip-address: ${spring.cloud.client.ip-address}
        #本服务的port
        port: ${server.port}
        #每隔15秒检查服务的健康状态
        health-check-interval: 15s

resilience4j:
  circuitbreaker:
    instances:
      cirA:
        #注册健康检查
        registerHealthIndicator: true
        #滑动窗口的大小
        slidingWindowSize: 5
        #half-open执行请求数
        permittedNumberOfCallsInHalfOpenState: 2
        #滑动窗口的类型
        slidingWindowType: TIME_BASED
        #最小的调用数量,只有达到10次才会计算滑动窗口的失败率
        minimumNumberOfCalls: 5
        #open -> half-open的等待时间
        waitDurationInOpenState: 2s
        #失败率,当失败率达到百分之50,熔断开启(open)
        failureRateThreshold: 30
        #事件缓存大小
        eventConsumerBufferSize: 10