server:
    port: 8090
    tomcat:
      #设置uri编码
      uri-encoding: UTF-8
      #设置等待队列的最大长度
      accept-count: 1000
      #设置最大链接数
      max-connections: 10000
      #链接建立超时时间
      connection-timeout: 1m
      #设置最大http表单提交大小
      max-http-form-post-size: 50MB
      #连接最大支持的请求数
      max-keep-alive-requests: 100
      #线程设置
      threads:
        #最大线程的数
        max: 500
        #最小的线程数
        min-spare: 50

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.86.128:3306/test?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: admin
      password: 123456
      #初始化连接数量，最大最小连接数
      initial-size: 5
      max-active: 10
      min-idle: 3
      #获取连接等待超时的时间
      max-wait: 600000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 1000000 #300000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1
      #申请连接的时候检测
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
      filters: stat
      stat-view-servlet:
        #allow: '*'
        #deny: 172.16.0.117
        login-username: druid
        login-password: druidzzlc123
        reset-enable: false
        url-pattern: '/druid/*'
      web-stat-filter:
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  redis:
    jedis:
      pool:
        enabled: true
        max-active:  8
        max-idle:  8
        min-idle: 0
    host: 192.168.86.128
    password: 123456
    database: 1
    port: 6379
    connect-timeout: 1m
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    #端口号
    port: 5672
    #用户名
    username: admin
    #密码
    password: x123456
    #主机号
    host: www.xiaolongwei.cn
    #虚拟主机
    virtual-host: /
    #缓存配置
    cache:
      #配置管道缓存
      channel:
        checkout-timeout: 5m
        size: 10
    #开启发布确认
    publisher-confirm-type: correlated
    #开启消息回退，交换机在收到生产者消息时候，发现没用匹配的路由，则会将消息发回生产者
    template:
      mandatory: true
    #开启消息回退
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.springboot.domain
  configuration:
    default-fetch-size: 100
    map-underscore-to-camel-case: true
    default-statement-timeout: 1000
    call-setters-on-nulls: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mq:
  exchange-name: ex1
  routing-key: oder
  ttl-exchange-name: tex
  ttl-routing-key: ttl

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 1800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true