spring:
  #设置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:47.96.12.138}:${DATASOURCE_PORT:23307}/fxkp?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
      username: ${DATASOURCE_USERNAME:root}
      password: ${DATASOURCE_PASSWORD:4ca31850774c707a58a77163a04905efQW}
      #初始化连接数量，最大最小连接数
      initial-size: 10
      max-active: 20
      min-idle: 5
      #获取连接等待超时的时间
      max-wait: 600000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 1000000 #300000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1
      #申请连接的时候检测
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
      filters: stat
      stat-view-servlet:
        #allow: '*'
        #deny: 172.16.0.117
        login-username: druid
        login-password: druidzzlc123
        reset-enable: false
        url-pattern: '/druid/*'
      web-stat-filter:
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  redis:
    host: ${REDIS_HOST:47.96.12.138}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:HskS4xsXVsEd1zHnopumdwTkgsvySa}
    database: 0
    lettuce:
      pool:
        max-active: 300

mybatis-plus:
  #配置mapper.xml文件路径
  mapper-locations: classpath:mapper/*.xml
  #实体类别名扫描路径
  type-aliases-package: com.sxkj.pay.entity
  configuration:
    #设置查询返回值数量
    default-fetch-size: 1000
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #语句执行超时10秒
    default-statement-timeout: 10
    #设置为空的字段
    call-setters-on-nulls: true
    #开启懒加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #日志输出方式
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-field: SCBJ
      logic-delete-value: 1
      logic-not-delete-value: 0