server:
  port: 9993
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: center
  #配置cloud
  cloud:
    #配置consul
    consul:
      #配置consul主机
      host: localhost
      #配置consul端口
      port: 8500
      #配置服务发现
      discovery:
        #配置服务名称
        service-name: home
        #配置服务实例id
        instance-id: ${spring.application.name}-${server.port}
        #是否注册服务
        register: true
        #使用ip地址注册
        prefer-ip-address: true
        #本服务ip
        ip-address: ${spring.cloud.client.ip-address}
        #本服务的port
        port: ${server.port}
        #每隔15秒检查服务的健康状态
        health-check-interval: 15s
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0



